# Generated by Django 3.2.3 on 2021-05-21 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_auto_20210521_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 21, 23, 32, 44, 862710)),
        ),
        migrations.AlterField(
            model_name='detail',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
