# Generated by Django 3.2.3 on 2021-05-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0004_alter_detail_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='comments',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='detail',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
